name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache
        uses: actions/cache@v5.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: 
          # An explicit key for restoring and saving the cache
          key: 
          # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
          restore-keys: # optional
          # The chunk size used to split up large files during upload, in bytes
          upload-chunk-size: # optional
          # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
          enableCrossOsArchive: # optional, default is false
          # Fail the workflow if cache entry is not found
          fail-on-cache-miss: # optional, default is false
          # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
          lookup-only: # optional, default is false
          # Run the post step to save the cache even if another step before fails
          save-always: # optional, default is false

      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Generate WASM bindings
        run: |
          wasm-bindgen \
            --out-dir dist \
            --target web \
            target/wasm32-unknown-unknown/release/blockman.wasm

      - name: Copy assets
        run: cp -r assets dist/assets

      - name: Copy index.html
        run: cp index.html dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        uses: actions/deploy-pages@v4
